--- #YAML:1.0
name: haver-client
version: 0.043
license: gpl
distribution_type: module
requires:
  Data::Dumper: 2.121
  Digest::SHA1: 2.01
  Haver: 0.043
  POE: 0.26
  perl: 5.6.1
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Haver::Client:
    file: lib/Haver/Client.pm
    version: 0.043
generated_by: Module::Build version 0.21
