---
name: Haver-Client
version: 0.08
author:
  - Dylan Hardison <dylan@haverdev.org>
  - Bryan Donlan <bdonlan@haverdev.org>
abstract: POE component for haver clients.
license: gpl
requires:
  Data::Dumper: 2.121
  Digest::SHA1: 2.01
  Haver::Core: 0.08
  perl: 5.8.0
provides:
  Haver::Client:
    file: lib/Haver/Client.pm
    version: 0.08
  Haver::Client::Failures:
    file: lib/Haver/Client/Failures.pm
    version: 0.08
generated_by: Module::Build version 0.26
